menu:
  Home: /
  Weekly: /categories/Weekly
  LeetCode: /categories/LeetCode
  Articles: /archives
  Drama: /categories/drama
  My: /about

profile:

  avatar: https://wsrv.nl/?url=raw.githubusercontent.com/huangshoucheng/picBed/master/work.jpg
  name: Bayesiano
  bio: Focusing
  github: https://github.com/Bayesianovich
  social:
    bilibili: https://space.bilibili.com/3493122969439010
    xiaohongshu: https://www.xiaohongshu.com/user/profile/5bfe7e7744363b0eaeaa1c62
    envelope: mailto:hsc2333work@gmail.com
    x-twitter: https://x.com/Huangsc_aimj

# Reward configuration
reward:
  enable: true
  title: 赞赏作者
  message: 您的支持是我最大的动力！
  # 由于您的 GitHub 仓库体积超过 jsDelivr 限制，这里使用 weserv 全球图片代理服务
  qrcode: https://wsrv.nl/?url=raw.githubusercontent.com/huangshoucheng/picBed/master/20260119194135.png
# Feature area configuration
feature:
  enabled: true

# Icon Mapping
tag_icons:
  Python: fab fa-python
  Linux: fab fa-linux
  Apple: fab fa-apple
  Docker: fab fa-docker
  Github: fab fa-github
  JavaScript: fab fa-js
  React: fab fa-react
  Vue: fab fa-vuejs
  Node.js: fab fa-node
  Git: fab fa-git-alt
  Android: fab fa-android
  iOS: fab fa-app-store-ios
  Swift: fab fa-swift
  Java: fab fa-java
  DP: fas fa-calculator
  Greedy: fas fa-hand-holding-usd
  DFS: fas fa-project-diagram
  BFS: fas fa-network-wired
  
category_icons:
  Programming: fas fa-code
  Life: fas fa-coffee
  Notes: fas fa-sticky-note
  Tools: fas fa-tools
  Thoughts: fas fa-lightbulb
  Weekly: fas fa-newspaper
  LeetCode: fas fa-laptop-code
  2025: fas fa-calendar-check
  2026: fas fa-calendar-plus
  Dynamic Programming: fas fa-calculator
  Greedy: fas fa-hand-holding-usd

# Category display rules
category_display:
  # Sidebar "Categories" widget
  sidebar:
    include:
      - Weekly
      - LeetCode
      - Life
      - Notes
      - Tools
      - Programming
      - Thoughts
    exclude:
      - 2025
      - 2026
      - 1
      - 2
      - 01
      - 02
      - Dynamic Programming
      - Greedy
      - Easy
      - Medium
      - Hard
      - DFS
      - BFS
  # Categories to hide from the homepage post list
  homepage_hide:
    - Weekly
    - LeetCode

# Table of Contents (TOC) Configuration
toc:
  collapse: true # Set to false to expand all sub-items by default
